### ISSUE TITLE
Assign a valid schema URL

### ISSUE THREAD

**Issue by ocastrup** [OCXStandard/OCX_Schema#5]
## Valid schema URL

The current schema version does not contain a valid URL:
```
xmlns:ocx="http://data.dnvgl.com/Schemas/ocxXMLSchema"
```
I propose to assign an URL pointing to the Consortium website and include the version number in the URL. The current schema is available at the Consortium website and has the following URL:

```
https://3docx.org/fileadmin/ocx_schema/V286/OCX_Schema.xsd
```

The next version of the schema should then contain the following xmlns namespace
```
https://3docx.org/fileadmin/ocx_schema/V287/OCX_Schema.xsd

**Comment by ocastrup** [comment]
A valid URL is implemented

**Comment by odegrand** [comment]
Please note that the following url doesn't work: https://3docx.org/fileadmin/ocx_schema/V287/OCX_Schema.xsd.

It seems that the correct one is https://3docx.org/ocx_schema/V287/OCX_Schema.xsd.

Moreover, due to the modification of the version number, the new url must be: https://3docx.org/ocx_schema/V300/OCX_Schema.xsd
